export const SONG_REPOSITORY = "SONGS";
export const SONG_NAMES_REPOSITORY = "SONG_NAMES";
export const SONG_VARIANTS_REPOSITORY = "SONG_VARIANTS";
export const CREATOR_REPOSITORY = "AUTHORS";
export const CSLINK_REPOSITORY = "ASLINKS";
export const USER_REPOSITORY = "USERS";