export const SONG_REPOSITORY = "SONGS";
export const SONG_TITLE_REPOSITORY = "SONG_NAMES";
export const SONG_VARIANTS_REPOSITORY = "SONG_VARIANTS";
export const CREATOR_REPOSITORY = "AUTHORS";
export const CSVLINK_REPOSITORY = "ASLINKS";
export const USER_REPOSITORY = "USERS";
export const MEDIA_REPOSITORY = "MEDIA";
export const SOURCE_REPOSITORY = "SOURCE";
export const TAG_REPOSITORY = "TAG";
export const PLAYLIST_REPOSITORY = "PLAYLIST";
export const GROUP_REPOSITORY = "GROUP";
export const PLAYLIST_ITEMS_REPOSITORY = "PLAYLIST_ITEMS";

export const GETTER_SOURCES_REPOSITORY = "GETTER_SOURCES";
export const GETTER_DOMAIN_REPOSITORY = "GETTER_DOMAINS";
export const GETTER_SEARCH_REPOSITORY = "GETTER_SEARCH";
export const GETTER_SUBURL_REPOSITORY = "GETTER_SUBURL";
export const GETTER_EXPLORE_REPOSITORY = "GETTER_EXPLORE";